Vagrant.configure("2") do |config|
    config.vm.box = "fedora/34-cloud-base"
    config.vm.box_check_update = false
    config.vm.hostname = "microshift"
    config.vm.network "private_network", ip: "192.168.56.40"
    config.vm.synced_folder "data", "/vagrant_data", type: 'virtualbox'
    config.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 3072
      v.cpus = 2
    end
    config.vm.provision "shell", path: "use_fedora_repo_from_tuna.sh"
    config.vm.provision "shell", path: "bootstrap.sh"
    config.vm.provision "shell", path: "install_microshift.sh"
  end