Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.synced_folder "data", "/vagrant_data", type: 'virtualbox'
    config.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 2048
      v.cpus = 2
    end
    
    config.vm.define "k3s" do |node|
      node.vm.network "private_network", ip: "192.168.56.50"
      node.vm.provision "shell", inline: <<-SHELL
        curl -sfL https://rancher-mirror.rancher.cn/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn sh -
      SHELL
    end
  end