Vagrant.configure("2") do |config|
    config.vm.box = "bento/centos-8"
    config.vm.box_check_update = false
    config.vm.hostname = "centos"
    config.vm.network "private_network", ip: "192.168.56.20"
    config.vm.synced_folder "data", "/vagrant_data", type: 'virtualbox'
    config.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 2048
      v.cpus = 2
    end
    config.vm.provision "shell", path: "bootstrap.sh"
  end